---
- name: Install dependencies via apt
  apt:
    name: "{{ item }}"
    cache_valid_time: 86400
    update_cache: yes
  with_items:
    - python-pip

- name: Install dependencies via pip
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - name: docker-py
      version: 1.1.0

- name: Check for drone
  stat:
    path: /usr/local/bin/drone
  register: drone_stat

- name: Ensure /etc/drone exists
  file:
    path: /etc/drone
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Pull drone container
  command: docker pull drone/drone:0.4

- name: Create drone configuration file
  template:
    src: dronerc.j2
    dest: /etc/drone/dronerc
    owner: root
    group: root
    mode: 0644

- name: stop drone
  command: docker stop drone

- name: rm drone
  command: docker rm drone

- name: Ensure drone is started
  command: "docker run --volume /var/lib/drone:/var/lib/drone --volume /var/run/docker.sock:/var/run/docker.sock {{drone_docker_additional_args}} --env-file /etc/drone/dronerc --restart=always --publish=8000:8000 --detach=true --name=drone drone/drone:0.4"
