---
- name: Install dependencies via apt
  apt:
    name: "{{ item }}"
    cache_valid_time: 86400
    update_cache: yes
  with_items:
    - python-pip

- name: Install dependencies via pip
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - name: docker-py
      version: 1.1.0

- name: Check for drone
  stat:
    path: /usr/local/bin/drone
  register: drone_stat

- name: Ensure /etc/drone exists
  file:
    path: /etc/drone
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Pull drone container
  command: docker pull drone/drone:0.5

- include: drone-master.yml
  when: drone_master == True

- include: drone-agent.yml
  when: drone_master == False

- name: Setup some cleanup tasks in cron
  cron: name={{item.name}}
        job={{item.job}}
        minute="0"
        hour="0"
        weekday="0"
  with_items:
    - {name: "clear_drone_cache", job: "find /var/lib/drone/cache -name '*.tar' | xargs rm"}
    - {name: "clear_exited_docker", job: "docker rm `docker ps -a | grep Exited | awk '{print $1 }'`"}
    - {name: "clear_docker_aq", job: "docker rmi `docker images -aq`"}
    - {name: "clear_docker_orphan_volumes", job: "docker volume ls -qf dangling=true | xargs -r docker volume rm"}
