---
- name: run drone
  command: docker run --volume /var/lib/drone:/var/lib/drone --volume /var/run/docker.sock:/var/run/docker.sock --env-file /etc/drone/dronerc --restart=always --publish=80:8000 --detach=true --name=drone drone/drone:0.4

- name: stop drone
  command: docker stop drone

- name: rm drone
  command: docker rm drone
